import Head from "next/head";
import EventCard from "@/components/EventCard";
import EventType from "@/components/EventType";
import { Container, Typography } from "@mui/material";

export default function Home() {
  return (
    <>
      <Head>
        <title>KUEventHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container component="main" maxWidth="lg">
        <Typography
          component="h1"
          sx={{ mb: 2, fontWeight: "bold", fontSize: "20px" }}
        >
          ประเภทกิจกรรม
        </Typography>
        <EventType />

        <Typography
          component="h1"
          sx={{ mt: 4, mb: 2, fontWeight: "bold", fontSize: "20px" }}
        >
          กิจกรรมทั้งหมด
        </Typography>
        <EventCard events={data} />
      </Container>
    </>
  );
}

export const data = [
  {
    id: 1,
    name: "ชื่อกิจกรรม",
    type: "กิจกรรมเพื่อสังคม",
    image:
      "https://t4.ftcdn.net/jpg/04/73/25/49/360_F_473254957_bxG9yf4ly7OBO5I0O5KABlN930GwaMQz.jpg",
    activity_hours: 4,
    total_seat: 30,
    date: "25 ธันวาคม 2566",
    start_time: "12.00",
    end_time: "16.00",
    location: "คณะวิทยาศาสตร์ มหาวิทยาลัยเกษตรศาสตร์",
  },
  {
    id: 2,
    name: "ชื่อกิจกรรม",
    type: "กิจกรรมมหาวิทยาลัย",
    image:
      "https://t4.ftcdn.net/jpg/04/73/25/49/360_F_473254957_bxG9yf4ly7OBO5I0O5KABlN930GwaMQz.jpg",
    activity_hours: 3,
    total_seat: 50,
    date: "22 ธันวาคม 2566",
    start_time: "17.00",
    end_time: "20.00",
    location: "คณะวิทยาศาสตร์ มหาวิทยาลัยเกษตรศาสตร์",
  },
];
