import Head from "next/head";
import EventCard from "@/components/EventCard";
import EventType from "@/components/EventType";
import { Container, Typography } from "@mui/material";
import { useQuery } from "@tanstack/react-query";
import { getEvents } from "@/services/events";

export default function Home() {
  const { data, isLoading } = useQuery({
    queryKey: ['events'],
    queryFn: () => getEvents()
  });

  return (
    <>
      <Head>
        <title>KUEventHub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container component="main" maxWidth="lg">
        <Typography
          component="h1"
          sx={{ mb: 2, fontWeight: "bold", fontSize: "20px" }}
        >
          ประเภทกิจกรรม
        </Typography>
        <EventType />

        <Typography
          component="h1"
          sx={{ mt: 4, mb: 2, fontWeight: "bold", fontSize: "20px" }}
        >
          กิจกรรมทั้งหมด
        </Typography>
        <EventCard events={data?.events} />
      </Container>
    </>
  );
}
